### ISSUE TITLE
feature (python venv)

### ISSUE THREAD

**Issue by scuzzilla** [agkozak/polyglot#11]
it would be nice to have the possibility to show if the python virtual environment is active

**Comment by agkozak** [comment]
Yes, I think that will work. Give me a few days. And thanks for the good suggestion.

**Comment by scuzzilla** [comment]
> Yes, I think that will work. Give me a few days. And thanks for the good suggestion.

Beautiful, can't wait to try it. I'm quite happy with polyglot! Using it with OpenBSD + KSH :)

**Comment by agkozak** [comment]
Try the `venv` branch of this repository. The new indicator works for `virtualenv`/`venv`/`pipenv`/`poetry`.

**Comment by scuzzilla** [comment]
> Try the `venv` branch of this repository. The new indicator works for `virtualenv`/`venv`/`pipenv`/`poetry`.

Many thanks for you work! just tested, it simply works :)
do you plan to merge it into master?

**Comment by agkozak** [comment]
Of course! Give me a few days to continue testing the changes. I'll need to update the documentation as well. I'll tell you when I merge the new feature. Thanks again for helping to make the prompt better.

**Comment by agkozak** [comment]
I just added better support for `conda`.

**Comment by scuzzilla** [comment]
within tmux env:
initial condition: I'm developing within a python venv (the prompt is showing the venv name as expected).
I start a new session, the prompt is still showing the python's venv name however the venv is not really active.

if I activate the python venv with (. bin/activate) everything is working fine.

**Comment by agkozak** [comment]
That's a pretty common problem with `tmux`, and I don't think it has anything to do with prompt. `tmux` sessions don't always have the environment variables you thought they would! I think you'll probably have to come up with a solution for your `.shrc`/`.kshrc` file. You might look at [what this guy does](https://www.mackorone.com/2020/02/23/tmux-and-venv.html).

**Comment by scuzzilla** [comment]
Thanks for the info, very useful. Now it's working.

**Comment by agkozak** [comment]
The virtual environment features are now part of the `master` branch and release `v1.11.0`. Thanks again, @scuzzilla, for the good idea.
