### ISSUE TITLE
In zsh when I switch to command mode the status does not reset if I hit enter or ctrl-c while still in command mode.

### ISSUE THREAD

**Issue by edklem** [agkozak/polyglot#12]
While in vi mode on zsh the ":" does not reset to "+" at start of the new prompt if you hit enter while still in vi cmd mode.
For example if you hit ESC and then "k" to go back through command history and just press enter to execute the command the new prompt will show  a ":" even though we are back in insert mode.

I have a one line fix that would go in the zsh section. I can send a PR if you like.
Thanks.

**Comment by agkozak** [comment]
You're absolutely right. Yes, go ahead and submit a PR -- I'll be interested to see how you fix it.

**Comment by agkozak** [comment]
Merged. Thank you so much for your contribution.

**Comment by edklem** [comment]
Sure no problem, and thank you for the project, I am digging it.
