### ISSUE TITLE
Theme and font?

### ISSUE THREAD

**Issue by galderz** [agkozak/polyglot#5]
I was wondering what are the fonts and them used in the screenshots? They look v nice :)

**Comment by agkozak** [comment]
I used [DejaVu Sans Mono](https://dejavu-fonts.github.io/). Give it a try!

**Comment by galderz** [comment]
Thanks, I'll have a try! Also, what is the theme of the terminal that you use?

**Comment by agkozak** [comment]
I can't remember exactly what I was doing the day I took those screenshots, but it looks like some variety of Monokai to me.
