### ISSUE TITLE
mksh $HOME not shortened to "~"

### ISSUE THREAD

**Issue by mabequinho** [agkozak/polyglot#6]
![imageedit_2_4886626563](https://user-images.githubusercontent.com/46428150/56464638-42627780-63c4-11e9-9c99-1bdf9c523fa2.png)
gentoo mksh56c

**Comment by agkozak** [comment]
It doesn't look as if the Polyglot Prompt has loaded - if it had, you'd be seeing something more like

    username ~ $

How are you sourcing (loading) the prompt?

**Comment by mabequinho** [comment]
I`m sorry Mr @agkozak  i should have mentioned that i commented the following line.

![imageedit_2_2087810289](https://user-images.githubusercontent.com/46428150/56465500-b1e06300-63d4-11e9-9bdf-db97595f746f.png)

> How are you sourcing (loading) the prompt?

`source ~/clones/polyglot/polyglot.sh
`

**Comment by agkozak** [comment]
It doesn't look as if the Polyglot Prompt has loaded - if it had, you'd be seeing something more like

    username ~ $

How are you sourcing (loading) the prompt?

**Comment by agkozak** [comment]
It looks as if your `$HOME` variable is set to `/home/erika/` (the trailing slash would be a bit unusual). Could you check the value by running

    echo $HOME

?

**Comment by mabequinho** [comment]
You`re right .
```
$ echo $HOME
/home/erika/

```

**Comment by mabequinho** [comment]
Same issue with bash, i really didn't manually set this value anywhere. I am closing, since it looks like an issue on my machine. Thanks for your time.

**Comment by shampee** [comment]
"${PWD/\\/home\\/USERNAME/\\~}"
