### ISSUE TITLE
Whats the difference between $ and % in the prompt?

### ISSUE THREAD

**Issue by kiedtl** [agkozak/polyglot#7]

**Comment by agkozak** [comment]
Bourne-style shells (`sh`, `ksh`, `bash`, and the like) use `$` as their default prompt character. `csh`-style shells use `%` by default. `zsh` shares features of both families of shells, and it uses `%` as its prompt character.

The Polyglot Prompt simply uses the prompt character that each shell would use by default. So you'll see `$` for all shells except `zsh`, which uses `%`.

**Comment by kiedtl** [comment]
Thanks! Awesome prompt BTW.

**Comment by agkozak** [comment]
Thanks!
