### ISSUE TITLE
dash login shell invocation issue

### ISSUE THREAD

**Issue by ghost** [agkozak/polyglot#8]
On Debian, dash version 0.5.10.2-5
On macOS, [brewed](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dash.rb) dash version 0.5.10.2

```
$ . ./polyglot.sh
-dash: 363: command: Illegal option -d
ls: : No such file or directory
Polyglot Prompt does not support your shell.
```

Just to make sure, [dash(1)](https://manpages.debian.org/dash)'s `command` in the Builtins subsection indeed does not list option `-d`.

https://github.com/agkozak/polyglot/blob/3c93f3ad32f7c03510b639d568f16192b3fdaa80/polyglot.sh#L362-L363

```
$ echo $0
-dash
```

Dash is invoked as a login shell in my use case. `-d` of `-dash` is evaluated by `command`, causing the error.

```
$ echo ${0#-} # "Remove Smallest Prefix Pattern" as described in dash(1)
dash
```

Substituting `"$0"` with `"${0#-}"` fixes the issue but you may want to implement the fix in a different (or better) way and so I didn't submit a pull request.

**Comment by agkozak** [comment]
Good catch! I never tested this prompt on a system where `dash` was the login shell.

I've done a quick fix for you on the `develop` branch, so go to the Polyglot Prompt directory and run

    git checkout develop
    git pull

and then restart `dash`. Let me know if the fix works.

**Comment by agkozak** [comment]
Oh, I just noticed that my quick fix was the same as your quick fix (I read your issue quickly because I'm on the way out of the house). Don't worry about changing branches -- just keep it the way you have it (with `"${0#-}"`), and I'll think about this for a few hours and get back to  you.

Thanks for helping to make the prompt better.

**Comment by agkozak** [comment]
Your fix is now on the `master` branch. Thanks for your help and your patience.
